version: "3.8"

services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: Krushnali
      MONGO_INITDB_ROOT_PASSWORD: Krushnali123
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: ./Backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env
    environment:
      MONGO_URI: "mongodb://Krushnali:Krushnali123@mongodb:27017/student-feedback?authSource=admin"
      FRONTEND_URL: "http://frontend"
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
